version: "3.7"

services:
  backend:
    build:
      context: ./server      
    restart: always
    networks:
      - backend_net
      - frontend_net
    ports:
      - 8081:8081
    environment:
      SECRET_KEY: "Habia una vez un barco chiquito"
      PORT: 8081
      DB_HOST: db
    depends_on:
        - db

  db:
    image: mongo:4.2.1-bionic
    restart: always
    networks:
      - backend_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysuperpassword      
    volumes:
      - api_db_vol:/data/db

  frontend:
    build:
      context: ./client
      args:
        BASE_URL: http://localhost:8081        
    restart: always
    networks:
      - frontend_net
    ports:
      - 3005:3005
    environment:
      SERVE_PORT: 3005
      
volumes:
  api_db_vol:

networks:
  backend_net:
  frontend_net:
